<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="image\1.jpg" />
    <None Remove="image\לוגו עם מסגרת.png" />
    <None Remove="image\לוגו קטן בלי רקע %282%29.png" />
    <None Remove="image\לוגו.png" />
    <None Remove="image\רקע.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BL\BL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="image\1.jpg" />
    <Resource Include="image\לוגו עם מסגרת.png" />
    <Resource Include="image\לוגו קטן בלי רקע (2).png" />
    <Resource Include="image\לוגו.png" />
    <Resource Include="image\רקע.png" />
  </ItemGroup>

</Project>
